### ISSUE TITLE
SortStrategyFactoryInterface is not being mapped to its default implementation

### ISSUE THREAD

**Issue by JJWesterkamp** [czim/laravel-datastore#2]
Missing a binding in [`DataStoreServiceProvider::registerInterfaces()`](https://github.com/czim/laravel-datastore/blob/master/src/Providers/DataStoreServiceProvider.php#L40):

```php
$this->app->singleton(SortStrategyFactoryInterface::class, SortStrategyFactory::class);
```

**Comment by czim** [comment]
Thanks, added to the provider in f308ce4cb21d98a9ad3bbda0fc1760d231862186
